carto_sync.config:
  type: config_object
  label: 'CARTO Sync settings'
  mapping:
    carto_id:
      type: text
      label: 'CARTO ID'
    carto_api_key:
      type: text
      label: 'CARTO API Key'
